
CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id INT REFERENCES roles (role_id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS tasks
(
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    time_when_created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    duration INTERVAL,
    time_when_finished TIMESTAMP,
    status VARCHAR(11) DEFAULT 'PENDING',
    priority VARCHAR(6) DEFAULT 'LOW',
    author_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    executor_id BIGINT NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000),
    time_when_created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    task_id BIGINT REFERENCES tasks (task_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS roles
(
    role_id INT PRIMARY KEY,
    name VARCHAR(8)
);

CREATE TABLE IF NOT EXISTS permissions
(
    permission_id INT PRIMARY KEY,
    name VARCHAR(8)
);

CREATE TABLE IF NOT EXISTS role_permissions
(
    role_id INT REFERENCES roles (role_id) ON DELETE CASCADE,
    permission_id INT REFERENCES permissions (permission_id)
);